title: Transfer Learning – Portfolio
description: Public-facing portfolio for transfer learning in clinical decision-making
theme: minima
markdown: kramdown

header_pages:
  - updates.md
  - resources.md

exclude:
  - README.md
